### ISSUE TITLE
Telegram File mirror Error ( even if I mirror the file as document)

### ISSUE THREAD

**Issue by meeker0** [lzzy12/python-aria-mirror-bot#198] opened 2021-01-01 15:05 UTC
whenever I try to mirror a video it gives me an error but _I also tried on documents_ as well ! It gives me no error ...but the bot also does nothing ! no active downloads in "status" !

**Comment by srijansaxena11** [comment] 2021-08-09 09:59
It throws this error:
![image](https://user-images.githubusercontent.com/34964694/128689658-90111948-0953-4462-a99a-dcc54cabe4a7.png)

**Comment by kzinthant-kas** [comment] 2021-08-09 13:52
I have got that error too. Is there any solution?

**Comment by lzzy12** [comment] 2021-08-09 13:59
Probably missing some step, maybe generating string session. Can't reproduce this error

**Comment by kzinthant-kas** [comment] 2021-08-09 14:27
I just edit the config.env. Is string session py mandatory to run?

**Comment by lzzy12** [comment] 2021-08-09 14:29
> I just edit the config.env. Is string session py mandatory to run?

So you skip a step writen in the readme and expect everything to work fine?

**Comment by kzinthant-kas** [comment] 2021-08-09 14:30
I might try it in some ways. I am using GitHub action for the bot hence user input cannot be easily done. Thanks for reply.

**Comment by kzinthant-kas** [comment] 2021-08-09 15:07
Just got it now! For those who can't figure out, the session string needs to be generated for the config.env as described in the readme.

**Comment by srijansaxena11** [comment] 2021-08-09 18:56
Doing something wrong here?
![image](https://user-images.githubusercontent.com/34964694/128759162-d64a5d6a-98d6-4c9f-8582-c9b2087f6b8b.png)

**Comment by lzzy12** [comment] 2021-08-18 09:12
> Doing something wrong here?
> ![image](https://user-images.githubusercontent.com/34964694/128759162-d64a5d6a-98d6-4c9f-8582-c9b2087f6b8b.png)

you need to provide the bot token and not your phone number while running generate_string_session.py

Closing this for now

**Closed by lzzy12** 2021-08-18 09:12 UTC
Labels: cannot-reproduce
